language: ruby
cache: bundler

dist: trusty
sudo: false

notifications:
  email: false

before_install:
  - gem update --system
  - gem install bundler -v '< 2'

matrix:
  include:
    - rvm: ruby-head
      gemfile: gemfiles/railsmaster.gemfile
    - rvm: jruby-9.2.5.0
      gemfile: gemfiles/jruby.gemfile
    - rvm: jruby-9.1.15.0
      gemfile: gemfiles/jruby.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/rails5.gemfile
  allow_failures:
    - rvm: ruby-head
      gemfile: gemfiles/railsmaster.gemfile
